### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by ruslan-khomiak** [eBay/digital-signature-nodejs-sdk#8]
I try to import `signMessage` method like this:
`const {signMessage} = require('digital-signature-nodejs-sdk');`

But I get an error:
`import { constants } from './constants';`
`^^^^^^`

`SyntaxError: Cannot use import statement outside a module`

Can you help me with it ?

**Comment by vhle-ms** [comment]
I'm having the same issue - I've raised a PR for this

**Comment by ruslan-khomiak** [comment]
@LokeshRishi Did you see it? Can merge?

**Comment by LokeshRishi** [comment]
@ruslan-khomiak Thanks for reporting the issue, I have published a new version of the package (3.0.0) which should resolve the issue.
@vhle-ms Thanks for the PR!

Let me know if you still see the issue.
